### ISSUE TITLE
无法安装hexo-service-worker

### ISSUE THREAD

**Issue by PDPENG** [lavas-project/hexo-service-worker#7]
`PS D:\blog> npm install --save hexo-service-worker
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: hexo-site@0.0.0
npm ERR! Found: hexo@5.4.0
npm ERR! node_modules/hexo
npm ERR!   hexo@"^5.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer hexo@"^3.2.2" from hexo-service-worker@1.0.1
npm ERR! node_modules/hexo-service-worker
npm ERR!   hexo-service-worker@"*" from the root project
`
尝试清理过缓存、更新npm版本（目前：v8.1.1）

**Comment by ifwwwx** [comment]
强制安装就可以npm install --force

**Comment by PDPENG** [comment]
已解决，谢谢
